; HEADER_BLOCK_START
; generated by Creality_Print V5.1.6.10470 on 2024-12-10 at 16:48:18
; total layer number: 10
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 2.00
; HEADER_BLOCK_END
; MINX = 105.95
; MINY = 96.06
; MINZ = -0.00
; MAXX = 113.10
; MAXY = 113.10
; MAXZ = 2.00
; THUMBNAIL_BLOCK_END
; THUMBNAIL_BLOCK_END
; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; support material extrusion width = 0.42mm
; first layer extrusion width = 0.50mm
; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; support material extrusion width = 0.42mm
; first layer extrusion width = 0.50mm
; EXECUTABLE_BLOCK_START
;TYPE:Custom
; filament start gcode
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
;AFTER_LAYER_CHANGE
;0.2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Washer 1.stl id:0 copy 0
;TYPE:Inner wall
;WIDTH:0.412097
;WIDTH:0.414196
;WIDTH:0.411335
;WIDTH:0.41429
;WIDTH:0.417174
;WIDTH:0.414292
;WIDTH:0.412096
;WIDTH:0.414188
;WIDTH:0.411337
;WIDTH:0.414294
;WIDTH:0.417174
;WIDTH:0.414301
;WIDTH:0.411718
;WIDTH:0.414172
;WIDTH:0.411331
;WIDTH:0.414295
;WIDTH:0.417173
;WIDTH:0.412097
;WIPE_START
;WIPE_END
;WIDTH:0.409076
;WIDTH:0.410815
;WIDTH:0.414172
;WIDTH:0.411396
;WIDTH:0.414287
;WIDTH:0.411382
;WIDTH:0.414294
;WIDTH:0.41139
;WIDTH:0.414318
;WIDTH:0.411383
;WIDTH:0.414312
;WIDTH:0.411397
;WIDTH:0.414292
;WIDTH:0.411393
;WIDTH:0.414188
;WIDTH:0.410827
;TYPE:Outer wall
;WIDTH:0.499999
;WIPE_START
;WIPE_END
; stop printing object Washer 1.stl id:0 copy 0
; printing object Washer 1.stl id:1 copy 0
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.412097
;WIDTH:0.414196
;WIDTH:0.411335
;WIDTH:0.41429
;WIDTH:0.417174
;WIDTH:0.414292
;WIDTH:0.412096
;WIDTH:0.414188
;WIDTH:0.411337
;WIDTH:0.414294
;WIDTH:0.417174
;WIDTH:0.414301
;WIDTH:0.411718
;WIDTH:0.414172
;WIDTH:0.411331
;WIDTH:0.414295
;WIDTH:0.417173
;WIDTH:0.412097
;WIPE_START
;WIPE_END
;WIDTH:0.409076
;WIDTH:0.410815
;WIDTH:0.414172
;WIDTH:0.411396
;WIDTH:0.414287
;WIDTH:0.411382
;WIDTH:0.414294
;WIDTH:0.41139
;WIDTH:0.414318
;WIDTH:0.411383
;WIDTH:0.414312
;WIDTH:0.411397
;WIDTH:0.414292
;WIDTH:0.411393
;WIDTH:0.414188
;WIDTH:0.410827
;TYPE:Outer wall
;WIDTH:0.499999
;WIPE_START
;WIPE_END
; stop printing object Washer 1.stl id:1 copy 0
;TIME_ELAPSED:5.449821
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.4
;WIPE_START
;WIPE_END
;AFTER_LAYER_CHANGE
;0.4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Washer 1.stl id:0 copy 0
;TYPE:Inner wall
;WIDTH:0.642743
;WIDTH:0.644402
;WIDTH:0.647166
;WIDTH:0.644311
;WIDTH:0.642749
;WIDTH:0.644397
;WIDTH:0.647196
;WIDTH:0.644319
;WIDTH:0.642746
;WIDTH:0.644379
;WIDTH:0.647167
;WIDTH:0.644301
;WIDTH:0.642748
;WIDTH:0.644383
;WIDTH:0.647171
;WIDTH:0.644294
;WIDTH:0.642743
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644404
;WIDTH:0.64237
;WIDTH:0.644301
;WIDTH:0.642376
;WIDTH:0.644288
;WIDTH:0.642366
;WIDTH:0.644294
;WIDTH:0.64237
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644311
;WIDTH:0.642375
;WIDTH:0.644293
;WIDTH:0.642372
;WIDTH:0.644404
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:0 copy 0
; printing object Washer 1.stl id:1 copy 0
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.642743
;WIDTH:0.644402
;WIDTH:0.647166
;WIDTH:0.644311
;WIDTH:0.642749
;WIDTH:0.644397
;WIDTH:0.647196
;WIDTH:0.644319
;WIDTH:0.642746
;WIDTH:0.644379
;WIDTH:0.647167
;WIDTH:0.644301
;WIDTH:0.642748
;WIDTH:0.644383
;WIDTH:0.647171
;WIDTH:0.644294
;WIDTH:0.642743
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644404
;WIDTH:0.64237
;WIDTH:0.644301
;WIDTH:0.642376
;WIDTH:0.644288
;WIDTH:0.642366
;WIDTH:0.644294
;WIDTH:0.64237
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644311
;WIDTH:0.642375
;WIDTH:0.644293
;WIDTH:0.642372
;WIDTH:0.644404
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:1 copy 0
;TIME_ELAPSED:9.831257
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.6
;WIPE_START
;WIPE_END
;AFTER_LAYER_CHANGE
;0.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Washer 1.stl id:0 copy 0
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642742
;WIDTH:0.644374
;WIDTH:0.647176
;WIDTH:0.644294
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644297
;WIDTH:0.642736
;WIDTH:0.644373
;WIDTH:0.647175
;WIDTH:0.644372
;WIDTH:0.642734
;WIDTH:0.644295
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644297
;WIDTH:0.642371
;WIDTH:0.6443
;WIDTH:0.642377
;WIDTH:0.644289
;WIDTH:0.642366
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644312
;WIDTH:0.642375
;WIDTH:0.644294
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644297
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:0 copy 0
; printing object Washer 1.stl id:1 copy 0
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642742
;WIDTH:0.644374
;WIDTH:0.647176
;WIDTH:0.644294
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644297
;WIDTH:0.642736
;WIDTH:0.644373
;WIDTH:0.647175
;WIDTH:0.644372
;WIDTH:0.642734
;WIDTH:0.644295
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644297
;WIDTH:0.642371
;WIDTH:0.6443
;WIDTH:0.642377
;WIDTH:0.644289
;WIDTH:0.642366
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644312
;WIDTH:0.642375
;WIDTH:0.644294
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644297
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:1 copy 0
;TIME_ELAPSED:14.200308
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.8
;WIPE_START
;WIPE_END
;AFTER_LAYER_CHANGE
;0.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Washer 1.stl id:0 copy 0
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642742
;WIDTH:0.644374
;WIDTH:0.647175
;WIDTH:0.644293
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644296
;WIDTH:0.642736
;WIDTH:0.644373
;WIDTH:0.647175
;WIDTH:0.644371
;WIDTH:0.642735
;WIDTH:0.644296
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644296
;WIDTH:0.64237
;WIDTH:0.644301
;WIDTH:0.642376
;WIDTH:0.644289
;WIDTH:0.642367
;WIDTH:0.644295
;WIDTH:0.64237
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644311
;WIDTH:0.642375
;WIDTH:0.644293
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644296
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:0 copy 0
; printing object Washer 1.stl id:1 copy 0
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642742
;WIDTH:0.644374
;WIDTH:0.647175
;WIDTH:0.644293
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644296
;WIDTH:0.642736
;WIDTH:0.644373
;WIDTH:0.647175
;WIDTH:0.644371
;WIDTH:0.642735
;WIDTH:0.644296
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644296
;WIDTH:0.64237
;WIDTH:0.644301
;WIDTH:0.642376
;WIDTH:0.644289
;WIDTH:0.642367
;WIDTH:0.644295
;WIDTH:0.64237
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644311
;WIDTH:0.642375
;WIDTH:0.644293
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644296
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:1 copy 0
;TIME_ELAPSED:18.571712
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1
;WIPE_START
;WIPE_END
;AFTER_LAYER_CHANGE
;1
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Washer 1.stl id:0 copy 0
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642743
;WIDTH:0.644375
;WIDTH:0.647175
;WIDTH:0.644293
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644297
;WIDTH:0.642737
;WIDTH:0.644373
;WIDTH:0.647174
;WIDTH:0.644372
;WIDTH:0.642734
;WIDTH:0.644295
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644297
;WIDTH:0.64237
;WIDTH:0.6443
;WIDTH:0.642376
;WIDTH:0.644288
;WIDTH:0.642365
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644311
;WIDTH:0.642375
;WIDTH:0.644293
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644297
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:0 copy 0
; printing object Washer 1.stl id:1 copy 0
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642743
;WIDTH:0.644375
;WIDTH:0.647175
;WIDTH:0.644293
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644297
;WIDTH:0.642737
;WIDTH:0.644373
;WIDTH:0.647174
;WIDTH:0.644372
;WIDTH:0.642734
;WIDTH:0.644295
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644297
;WIDTH:0.64237
;WIDTH:0.6443
;WIDTH:0.642376
;WIDTH:0.644288
;WIDTH:0.642365
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644311
;WIDTH:0.642375
;WIDTH:0.644293
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644297
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:1 copy 0
;TIME_ELAPSED:22.943323
;LAYER_CHANGE
;Z:1.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.2
;WIPE_START
;WIPE_END
;AFTER_LAYER_CHANGE
;1.2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Washer 1.stl id:0 copy 0
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642742
;WIDTH:0.644374
;WIDTH:0.647176
;WIDTH:0.644294
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644296
;WIDTH:0.642737
;WIDTH:0.644373
;WIDTH:0.647175
;WIDTH:0.644372
;WIDTH:0.642734
;WIDTH:0.644295
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644296
;WIDTH:0.642371
;WIDTH:0.6443
;WIDTH:0.642376
;WIDTH:0.644289
;WIDTH:0.642367
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644312
;WIDTH:0.642375
;WIDTH:0.644294
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644296
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:0 copy 0
; printing object Washer 1.stl id:1 copy 0
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642742
;WIDTH:0.644374
;WIDTH:0.647176
;WIDTH:0.644294
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644296
;WIDTH:0.642737
;WIDTH:0.644373
;WIDTH:0.647175
;WIDTH:0.644372
;WIDTH:0.642734
;WIDTH:0.644295
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644296
;WIDTH:0.642371
;WIDTH:0.6443
;WIDTH:0.642376
;WIDTH:0.644289
;WIDTH:0.642367
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644312
;WIDTH:0.642375
;WIDTH:0.644294
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644296
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:1 copy 0
;TIME_ELAPSED:27.315166
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.4
;WIPE_START
;WIPE_END
;AFTER_LAYER_CHANGE
;1.4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Washer 1.stl id:0 copy 0
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642743
;WIDTH:0.644375
;WIDTH:0.647176
;WIDTH:0.644294
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644297
;WIDTH:0.642736
;WIDTH:0.644373
;WIDTH:0.647174
;WIDTH:0.644373
;WIDTH:0.642734
;WIDTH:0.644295
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644297
;WIDTH:0.642371
;WIDTH:0.644301
;WIDTH:0.642376
;WIDTH:0.644289
;WIDTH:0.642367
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644311
;WIDTH:0.642375
;WIDTH:0.644294
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644297
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:0 copy 0
; printing object Washer 1.stl id:1 copy 0
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642743
;WIDTH:0.644375
;WIDTH:0.647176
;WIDTH:0.644294
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644297
;WIDTH:0.642736
;WIDTH:0.644373
;WIDTH:0.647174
;WIDTH:0.644373
;WIDTH:0.642734
;WIDTH:0.644295
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644297
;WIDTH:0.642371
;WIDTH:0.644301
;WIDTH:0.642376
;WIDTH:0.644289
;WIDTH:0.642367
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644311
;WIDTH:0.642375
;WIDTH:0.644294
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644297
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:1 copy 0
;TIME_ELAPSED:31.687231
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.6
;WIPE_START
;WIPE_END
;AFTER_LAYER_CHANGE
;1.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Washer 1.stl id:0 copy 0
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642742
;WIDTH:0.644375
;WIDTH:0.647175
;WIDTH:0.644294
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644297
;WIDTH:0.642737
;WIDTH:0.644373
;WIDTH:0.647175
;WIDTH:0.644372
;WIDTH:0.642734
;WIDTH:0.644295
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644297
;WIDTH:0.64237
;WIDTH:0.6443
;WIDTH:0.642377
;WIDTH:0.644289
;WIDTH:0.642367
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644312
;WIDTH:0.642375
;WIDTH:0.644294
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644297
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:0 copy 0
; printing object Washer 1.stl id:1 copy 0
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.647179
;WIDTH:0.644319
;WIDTH:0.642742
;WIDTH:0.644375
;WIDTH:0.647175
;WIDTH:0.644294
;WIDTH:0.642745
;WIDTH:0.644403
;WIDTH:0.647176
;WIDTH:0.644297
;WIDTH:0.642737
;WIDTH:0.644373
;WIDTH:0.647175
;WIDTH:0.644372
;WIDTH:0.642734
;WIDTH:0.644295
;WIDTH:0.647173
;WIDTH:0.647179
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644297
;WIDTH:0.64237
;WIDTH:0.6443
;WIDTH:0.642377
;WIDTH:0.644289
;WIDTH:0.642367
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644312
;WIDTH:0.642375
;WIDTH:0.644294
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644297
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:1 copy 0
;TIME_ELAPSED:36.057747
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.8
;WIPE_START
;WIPE_END
;AFTER_LAYER_CHANGE
;1.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Washer 1.stl id:0 copy 0
;TYPE:Inner wall
;WIDTH:0.642743
;WIDTH:0.644402
;WIDTH:0.647167
;WIDTH:0.644311
;WIDTH:0.642749
;WIDTH:0.644398
;WIDTH:0.647196
;WIDTH:0.644318
;WIDTH:0.642746
;WIDTH:0.644378
;WIDTH:0.647167
;WIDTH:0.6443
;WIDTH:0.642748
;WIDTH:0.644383
;WIDTH:0.647171
;WIDTH:0.644295
;WIDTH:0.642743
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644297
;WIDTH:0.64237
;WIDTH:0.6443
;WIDTH:0.642377
;WIDTH:0.644288
;WIDTH:0.642367
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644311
;WIDTH:0.642375
;WIDTH:0.644293
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644297
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:0 copy 0
; printing object Washer 1.stl id:1 copy 0
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.642743
;WIDTH:0.644402
;WIDTH:0.647167
;WIDTH:0.644311
;WIDTH:0.642749
;WIDTH:0.644398
;WIDTH:0.647196
;WIDTH:0.644318
;WIDTH:0.642746
;WIDTH:0.644378
;WIDTH:0.647167
;WIDTH:0.6443
;WIDTH:0.642748
;WIDTH:0.644383
;WIDTH:0.647171
;WIDTH:0.644295
;WIDTH:0.642743
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;TYPE:Inner wall
;WIDTH:0.644297
;WIDTH:0.64237
;WIDTH:0.6443
;WIDTH:0.642377
;WIDTH:0.644288
;WIDTH:0.642367
;WIDTH:0.644295
;WIDTH:0.642369
;WIDTH:0.644319
;WIDTH:0.642386
;WIDTH:0.644311
;WIDTH:0.642375
;WIDTH:0.644293
;WIDTH:0.642371
;WIDTH:0.644318
;WIDTH:0.642384
;WIDTH:0.644297
;TYPE:Outer wall
;WIDTH:0.419999
; stop printing object Washer 1.stl id:1 copy 0
;TIME_ELAPSED:40.431049
;LAYER_CHANGE
;Z:2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2
;WIPE_START
;WIPE_END
;AFTER_LAYER_CHANGE
;2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Washer 1.stl id:0 copy 0
;WIPE_START
;WIPE_END
;WIPE_START
;WIPE_END
;TYPE:Top surface
;WIDTH:0.444878
;WIPE_START
;WIPE_END
;WIPE_START
;WIPE_END
;WIPE_START
;WIPE_END
; stop printing object Washer 1.stl id:0 copy 0
; printing object Washer 1.stl id:1 copy 0
;WIPE_START
;WIPE_END
;TYPE:Outer wall
;WIDTH:0.419999
;WIPE_START
;WIPE_END
;WIPE_START
;WIPE_END
;TYPE:Top surface
;WIDTH:0.444878
;WIPE_START
;WIPE_END
;WIPE_START
;WIPE_END
;WIPE_START
;WIPE_END
; stop printing object Washer 1.stl id:1 copy 0
;TIME_ELAPSED:45.873775
;WIPE_START
;WIPE_END
;TYPE:Custom
; filament end gcode 
; EXECUTABLE_BLOCK_END
; filament used [mm] = 39.84
; filament used [cm3] = 0.10
; filament used [g] = 0.12
; filament cost = 0.00; total filament used [g] = 0.12
; total filament cost = 0.00
; total layers count = 10
; total estimated time: 45s
; filament used [mm]: 39.84
; type_times_1 =  1,0.675759; 2,0.846703; 8,6.252717; 9,1.037498; 10,36.269321; 
; type_times_2 =  0,6.252717; 1,16.565144; 2,19.616964; 6,2.614575; 18,0.862280; 
; type_times_3 =  45.912
; estimated printing time (normal mode) = 45s
; CONFIG_BLOCK_START
; absolute_correction = 0
; accel_to_decel_enable = 1
; accel_to_decel_factor = 100%
; acceleration_limit_mess = [[0.5,1.0,100,6000],[1.0,1.5,80,5500],[1.5,2.0,60,5000]]
; acceleration_limit_mess_enable = 0
; activate_air_filtration = 0
; activate_chamber_temp_control = 1
; adaptive_bed_mesh_margin = 0
; additional_cooling_fan_speed = 80
; ai_infill = 0
; alternate_extra_wall = 0
; arc_tolerance = 12
; area_fill = 50
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottle_cost = 0
; bottle_volume = 1000
; bottle_weight = 1
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 25
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 35
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; compatible_machine_expression_group = 
; compatible_printers_condition = 
; compatible_prints_condition = 
; compatible_process_expression_group = 
; complete_print_exhaust_fan_speed = 80
; cool_cds_fan_start_at_height = 0.5
; cool_plate_temp = 50
; cool_plate_temp_initial_layer = 50
; cool_special_cds_fan_speed = 0
; cooling_tube_length = 0
; cooling_tube_retraction = 0
; counterbore_hole_bridging = none
; cpp_version = 
; creality_flush_time = 86
; curr_bed_type = High Temp Plate
; default_acceleration = 12000
; default_filament_colour = #3ddf56
; default_filament_profile = "Hyper PLA"
; default_filament_type = PLA
; default_jerk = 20
; default_print_profile = 0.20mm Standard
; default_sla_material_profile = 
; default_sla_print_profile = 
; deretraction_speed = 40
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = 
; disable_m73 = 0
; display_height = 68
; display_mirror_x = 1
; display_mirror_y = 0
; display_orientation = portrait
; display_pixels_x = 2560
; display_pixels_y = 1440
; display_width = 120
; dont_filter_internal_bridges = disabled
; draft_shield = disabled
; during_print_exhaust_fan_speed = 60
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; elefant_foot_min_width = 0.2
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 1
; enable_filament_ramming = 0
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_special_area_additional_cooling_fan = 0
; enable_support = 1
; enforce_support_layers = 0
; eng_plate_temp = 50
; eng_plate_temp_initial_layer = 50
; ensure_vertical_shell_thickness = ensure_all
; epoxy_resin_plate_temp = 40
; epoxy_resin_plate_temp_initial_layer = 40
; exclude_object = 1
; exposure_time = 10
; extra_loading_move = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 101
; extruder_clearance_height_to_rod = 45
; extruder_clearance_radius = 45
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; faded_layers = 10
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; fast_tilt_time = 5
; filament_colour = #3ddf56
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 18
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.95
; filament_ids = 04001
; filament_is_support = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 18
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_lift_above = 0
; filament_retract_lift_below = 0
; filament_retract_lift_enforce = All Surfaces
; filament_settings_id = 
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Creality
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; first_layer_sequence_choice = Auto
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.7
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gamma_correction = 1
; gap_fill_target = everywhere
; gap_infill_speed = 300
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; hollowing_closing_distance = 2
; hollowing_enable = 0
; hollowing_min_thickness = 3
; hollowing_quality = 0.5
; host_type = octoprint
; hot_plate_temp = 50
; hot_plate_temp_initial_layer = 50
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_direction = 45
; infill_jerk = 20
; infill_wall_overlap = 30%
; inherits = MyKlipper 0.4 nozzle
; inherits_group = 
; initial_exposure_time = 15
; initial_layer_acceleration = 1000
; initial_layer_height = 0.3
; initial_layer_infill_speed = 105
; initial_layer_jerk = 20
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 60
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 20
; inner_wall_line_width = 0.45
; inner_wall_speed = 300
; interface_shells = 0
; internal_bridge_flow = 1
; internal_bridge_speed = 70
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_flow = 10%
; ironing_pattern = zig-zag
; ironing_spacing = 0.15
; ironing_speed = 100
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; line_width = 0.42
; long_retractions_when_cut = 0
; machine_LED_light_exist = 1
; machine_end_gcode = END_PRINT
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 20000
; machine_max_acceleration_retracting = 5000
; machine_max_acceleration_travel = 20000
; machine_max_acceleration_x = 20000
; machine_max_acceleration_y = 20000
; machine_max_acceleration_z = 500
; machine_max_jerk_e = 10
; machine_max_jerk_x = 20
; machine_max_jerk_y = 20
; machine_max_jerk_z = 5
; machine_max_speed_e = 100
; machine_max_speed_x = 800
; machine_max_speed_y = 800
; machine_max_speed_z = 30
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_platform_motion_enable = 1
; machine_start_gcode = M140 S0\nM104 S0 \nSTART_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single]
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; material_colour = #29B2B2
; material_correction = 1,1,1
; material_correction_x = 1
; material_correction_y = 1
; material_correction_z = 1
; material_density = 1
; material_flow_dependent_temperature = 0
; material_flow_temp_graph = [[3.0,210],  [10.0,220],  [12.0,230]]
; material_print_speed = fast
; material_type = Tough
; material_vendor = 
; max_bridge_length = 10
; max_exposure_time = 100
; max_initial_exposure_time = 150
; max_layer_height = 0.3
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_exposure_time = 0
; min_feature_size = 25%
; min_initial_exposure_time = 0
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 230
; nozzle_temperature_initial_layer = 230
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = brass
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 1
; ooze_prevention = 0
; outer_wall_acceleration = 5000
; outer_wall_jerk = 20
; outer_wall_line_width = 0.42
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; pad_around_object = 0
; pad_around_object_everywhere = 0
; pad_brim_size = 1.6
; pad_enable = 1
; pad_max_merge_distance = 50
; pad_object_connector_penetration = 0.3
; pad_object_connector_stride = 10
; pad_object_connector_width = 0.5
; pad_object_gap = 1
; pad_wall_height = 0
; pad_wall_slope = 90
; pad_wall_thickness = 2
; parking_pos_retraction = 0
; post_process = 
; precise_outer_wall = 0
; preferred_orientation = 0
; preset_name = 
; preset_names = 
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_enhance_type = chamfer
; prime_tower_position_type = Middle Upper
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = 
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 
; printable_area = 0x0,220x0,220x220,0x220
; printable_height = 250
; printer_model = K1
; printer_notes = 
; printer_settings_id = 
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 0
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; relative_correction = 1,1
; relative_correction_x = 1
; relative_correction_y = 1
; relative_correction_z = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 1
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.5
; retraction_minimum_travel = 1
; retraction_speed = 40
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; sla_material_settings_id = 
; sla_print_settings_id = 
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 4
; slow_down_layers = 0
; slow_down_min_speed = 10
; slow_tilt_time = 8
; slowdown_for_curled_perimeters = 0
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; software_version = V5.1.6.10470
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = cubic
; sparse_infill_speed = 250
; speed_limit_to_height = [[100,150,100,6000],[150,200,80,5500],[200,250,60,5000]]
; speed_limit_to_height_enable = 1
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 1
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 1
; support_angle = 0
; support_base_diameter = 4
; support_base_height = 1
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_base_safety_distance = 1
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_buildplate_only = 0
; support_chamber_temp_control = 0
; support_critical_angle = 45
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_head_front_diameter = 0.4
; support_head_penetration = 0.2
; support_head_width = 1
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.42
; support_material_interface_fan_speed = -1
; support_max_bridge_length = 15
; support_max_bridges_on_pillar = 3
; support_max_pillar_link_distance = 10
; support_multi_bed_types = 0
; support_object_elevation = 5
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_pillar_connection_mode = dynamic
; support_pillar_diameter = 1
; support_pillar_widening_factor = 0
; support_points_density_relative = 100
; support_points_minimal_distance = 1
; support_remove_small_overhang = 1
; support_small_pillar_diameter_percent = 50%
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = tree(auto)
; supports_enable = 1
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_plate_temp = 50
; textured_plate_temp_initial_layer = 50
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 96x96,300x300
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_shell_layers = 4
; top_shell_thickness = 0.6
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 5000
; top_surface_jerk = 20
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 12000
; travel_jerk = 20
; travel_speed = 500
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; tree_support_with_infill = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 2
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 110.000
; wipe_tower_y = 220.000
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; z_offset = 0
; first_layer_bed_temperature = 50
; bed_shape = 0x0,220x0,220x220,0x220
; first_layer_temperature = 230
; first_layer_height = 0.200
; CONFIG_BLOCK_END
; gcode_lines = 4880
