; generated by PrusaSlicer 2.8.1+MacOS-arm64 on 2026-09-28 at 13:00:00 UTC

; external perimeters extrusion width = 0.45mm
M73 P0 R52
G90
; (movimentos G-code omitidos)
M84 ; disable motors
; objects_info = {"objects":[{"name":"Ana","polygon":[[1,1]]},{"name":"Bia","polygon":[[2,2]]}]}

; filament used [mm] = 2310.42, 405.10
; filament used [cm3] = 5.56, 0.97
; filament used [g] = 6.95, 1.22
; filament cost = 0.21, 0.04
; total filament used [g] = 8.17
; total filament cost = 0.25
; estimated printing time (normal mode) = 1h 2m 3s
; estimated first layer printing time (normal mode) = 4m 10s

; prusaslicer_config = begin
; filament_colour = #FF8000;#FFFFFF
; filament_type = PETG;PLA
; printer_model = MK4
; prusaslicer_config = end
