; G-Code generated by Simplify3D(R) Version 4.1.2
; Nov 12, 2019 at 12:24:10 PM
; Settings Summary
;   processName,Process1
;   applyToModels,low_cube
;   profileName,Zaribo MK3 Quality (PLA) (modified)
;   profileVersion,2019-11-10 22:03:11
;   baseProfile,Default
;   printMaterial,PLA -BMG
;   printQuality,0.2
;   printExtruders,
;   extruderName,Primary Extruder
;   extruderToolheadNumber,0
;   extruderDiameter,0.4
;   extruderAutoWidth,0
;   extruderWidth,0.36
;   extrusionMultiplier,0.9
;   extruderUseRetract,1
;   extruderRetractionDistance,1
;   extruderExtraRestartDistance,0
;   extruderRetractionZLift,0.5
;   extruderRetractionSpeed,1500
;   extruderUseCoasting,0
;   extruderCoastingDistance,0.05
;   extruderUseWipe,0
;   extruderWipeDistance,2
;   primaryExtruder,0
;   layerHeight,0.2
;   topSolidLayers,0
;   bottomSolidLayers,3
;   perimeterOutlines,2
;   printPerimetersInsideOut,1
;   startPointOption,3
;   startPointOriginX,0
;   startPointOriginY,300
;   sequentialIslands,0
;   spiralVaseMode,0
;   firstLayerHeightPercentage,200
;   firstLayerWidthPercentage,115
;   firstLayerUnderspeed,0.3
;   useRaft,0
;   raftExtruder,0
;   raftTopLayers,3
;   raftBaseLayers,2
;   raftOffset,8
;   raftSeparationDistance,0.11
;   raftTopInfill,100
;   aboveRaftSpeedMultiplier,0.3
;   useSkirt,0
;   skirtExtruder,0
;   skirtLayers,1
;   skirtOutlines,20
;   skirtOffset,0
;   usePrimePillar,0
;   primePillarExtruder,999
;   primePillarWidth,12
;   primePillarLocation,7
;   primePillarSpeedMultiplier,1
;   useOozeShield,0
;   oozeShieldExtruder,999
;   oozeShieldOffset,2
;   oozeShieldOutlines,1
;   oozeShieldSidewallShape,1
;   oozeShieldSidewallAngle,30
;   oozeShieldSpeedMultiplier,1
;   infillExtruder,0
;   internalInfillPattern,Fast Honeycomb
;   externalInfillPattern,Rectilinear
;   infillPercentage,0
;   outlineOverlapPercentage,30
;   infillExtrusionWidthPercentage,105
;   minInfillLength,1
;   infillLayerInterval,1
;   internalInfillAngles,0
;   overlapInternalInfillAngles,0
;   externalInfillAngles,45,-45
;   generateSupport,1
;   supportExtruder,0
;   supportInfillPercentage,15
;   supportExtraInflation,0.3
;   supportBaseLayers,1
;   denseSupportExtruder,0
;   denseSupportLayers,1
;   denseSupportInfillPercentage,50
;   supportLayerInterval,1
;   supportHorizontalPartOffset,0.25
;   supportUpperSeparationLayers,1
;   supportLowerSeparationLayers,1
;   supportType,0
;   supportGridSpacing,2
;   maxOverhangAngle,45
;   supportAngles,0
;   temperatureName,Primary Extruder,Heated Bed
;   temperatureNumber,0,0
;   temperatureSetpointCount,2,1
;   temperatureSetpointLayers,1,2,1
;   temperatureSetpointTemperatures,215,200,55
;   temperatureStabilizeAtStartup,1,1
;   temperatureHeatedBed,0,1
;   fanLayers,1,2
;   fanSpeeds,0,75
;   blipFanToFullPower,0
;   adjustSpeedForCooling,1
;   minSpeedLayerTime,15
;   minCoolingSpeedSlowdown,20
;   increaseFanForCooling,0
;   minFanLayerTime,45
;   maxCoolingFanSpeed,100
;   increaseFanForBridging,0
;   bridgingFanSpeed,100
;   use5D,1
;   relativeEdistances,1
;   allowEaxisZeroing,1
;   independentExtruderAxes,0
;   includeM10123,0
;   stickySupport,1
;   applyToolheadOffsets,0
;   gcodeXoffset,0
;   gcodeYoffset,0
;   gcodeZoffset,0
;   overrideMachineDefinition,1
;   machineTypeOverride,0
;   strokeXoverride,250
;   strokeYoverride,210
;   strokeZoverride,210
;   originOffsetXoverride,0
;   originOffsetYoverride,0
;   originOffsetZoverride,0
;   homeXdirOverride,-1
;   homeYdirOverride,-1
;   homeZdirOverride,-1
;   flipXoverride,1
;   flipYoverride,-1
;   flipZoverride,1
;   toolheadOffsets,0,0|0,0|0,0|0,0|0,0|0,0
;   overrideFirmwareConfiguration,0
;   firmwareTypeOverride,RepRap (Marlin/Repetier/Sprinter)
;   GPXconfigOverride,r2
;   baudRateOverride,115200
;   overridePrinterModels,0
;   printerModelsOverride
;   startingGcode,G90 ; use absolute coordinates,M83 ; extruder relative mode,,;====== start preheat start script ==============================================================,,G28 W; home all without mesh bed level,G0 X60 Y-3 Z80; move extruder above bed keep extruder in front for cleaning and checking,,M104 S160 T0; pre-heat extruder to 160C ,M140 S[bed0_temperature] ; this will take the layer 1 temperature for bed 0,M190 S[bed0_temperature] ; wait for bed temp,,G80 N7; mesh bed leveling set 3x3 5x5 or 7x7 in settings menu,,M104S[extruder0_temperature] ; set extruder temperature,M109 S[extruder0_temperature]  ; wait for extruder temp,,;====== end preheat start script ================================================================,,M900 K20 ;,,M205 X8 ; jerk x standard 15,M205 Y8 ; jerk y standard 15,M205 E0.33 ; jerk e axis,M201 E180 ; e axis acceleration,,G1 Y-3.0 F1000.0 ; go outside print area,G92 E0.0,,G1 E8 ; Purge Bubble,G1 X60.0 E7.0  F1000.0 ; intro line,G1 X100.0 E8  F1000.0 ; intro line,G92 E0.0,
;   layerChangeGcode,G1 [current_Z_position] F10000;
;   retractionGcode,
;   toolChangeGcode,
;   endingGcode,M104 S0 ; turn off temperature,M140 S0 ; turn off heatbed,M107 ; turn off fan,G1 F1000.0 ; set feed rate,G1 E-3 ; retract,G1 X0 Y200 F7200 ; home XY axis,,M84 ; disable motors
;   exportFileFormat,gcode
;   celebration,0
;   celebrationSong,Funky Town
;   postProcessing,{REPLACE "; outer perimeter\n" "; outer perimeter\nM204 S600\n"},{REPLACE "; inner perimeter\n" "; inner perimeter\nM204 S1000\n"},{REPLACE "; solid layer\n" "; solid layer\nM204 S1200\n"},{REPLACE "; infill\n" "; infill\nM204 S1500\n"}
;   defaultSpeed,2400
;   outlineUnderspeed,0.4
;   solidInfillUnderspeed,0.8
;   supportUnderspeed,0.4
;   rapidXYspeed,8400
;   rapidZspeed,3600
;   minBridgingArea,5
;   bridgingExtraInflation,1
;   bridgingExtrusionMultiplier,1
;   bridgingSpeedMultiplier,0.95
;   useFixedBridgingAngle,0
;   fixedBridgingAngle,0
;   applyBridgingToPerimeters,0
;   filamentDiameters,1.75|1.75|1.75|1.75|1.75|1.75
;   filamentPricesPerKg,24|46|46|46|46|46
;   filamentDensities,1.25|1.25|1.25|1.25|1.25|1.25
;   useMinPrintHeight,0
;   minPrintHeight,0
;   useMaxPrintHeight,0
;   maxPrintHeight,0
;   useDiaphragm,0
;   diaphragmLayerInterval,20
;   robustSlicing,1
;   mergeAllIntoSolid,1
;   onlyRetractWhenCrossingOutline,0
;   retractBetweenLayers,0
;   useRetractionMinTravel,1
;   retractionMinTravel,1
;   retractWhileWiping,1
;   onlyWipeOutlines,1
;   avoidCrossingOutline,1
;   maxMovementDetourFactor,3
;   toolChangeRetractionDistance,12
;   toolChangeExtraRestartDistance,-0.5
;   toolChangeRetractionSpeed,600
;   externalThinWallType,1
;   internalThinWallType,2
;   thinWallAllowedOverlapPercentage,25
;   singleExtrusionMinLength,1
;   singleExtrusionMinPrintingWidthPercentage,50
;   singleExtrusionMaxPrintingWidthPercentage,200
;   singleExtrusionEndpointExtension,0.2
;   horizontalSizeCompensation,0
;====== start preheat start script ==============================================================
;====== end preheat start script ================================================================
; process Process1
; layer 1, Z = 0.400
; feature inner perimeter
; tool H0.400 W0.414
; feature outer perimeter
; feature solid layer
; layer 2, Z = 0.600
; feature inner perimeter
; tool H0.200 W0.360
; feature outer perimeter
; feature solid layer
; layer 3, Z = 0.800
; feature inner perimeter
; feature outer perimeter
; feature solid layer
; layer 4, Z = 1.000
; feature inner perimeter
; feature outer perimeter
; layer 5, Z = 1.200
; feature inner perimeter
; feature outer perimeter
; layer 6, Z = 1.400
; feature inner perimeter
; feature outer perimeter
; layer 7, Z = 1.600
; feature inner perimeter
; feature outer perimeter
; layer 8, Z = 1.800
; feature inner perimeter
; feature outer perimeter
; layer 9, Z = 2.000
; feature inner perimeter
; feature outer perimeter
; layer 10, Z = 2.200
; feature inner perimeter
; feature outer perimeter
; layer 11, Z = 2.400
; feature inner perimeter
; feature outer perimeter
; layer 12, Z = 2.600
; feature inner perimeter
; feature outer perimeter
; layer 13, Z = 2.800
; feature inner perimeter
; feature outer perimeter
; layer 14, Z = 3.000
; feature inner perimeter
; feature outer perimeter
; layer 15, Z = 3.200
; feature inner perimeter
; feature outer perimeter
; layer 16, Z = 3.400
; feature inner perimeter
; feature outer perimeter
; layer 17, Z = 3.600
; feature inner perimeter
; feature outer perimeter
; layer 18, Z = 3.800
; feature inner perimeter
; feature outer perimeter
; layer 19, Z = 4.000
; feature inner perimeter
; feature outer perimeter
; layer 20, Z = 4.200
; feature inner perimeter
; feature outer perimeter
; layer 21, Z = 4.400
; feature inner perimeter
; feature outer perimeter
; layer 22, Z = 4.600
; feature inner perimeter
; feature outer perimeter
; layer 23, Z = 4.800
; feature inner perimeter
; feature outer perimeter
; layer 24, Z = 5.000
; feature inner perimeter
; feature outer perimeter
; layer 25, Z = 5.200
; feature inner perimeter
; feature outer perimeter
; layer 26, Z = 5.400
; feature inner perimeter
; feature outer perimeter
; layer 27, Z = 5.600
; feature inner perimeter
; feature outer perimeter
; layer 28, Z = 5.800
; feature inner perimeter
; feature outer perimeter
; layer 29, Z = 6.000
; feature inner perimeter
; feature outer perimeter
; layer 30, Z = 6.200
; feature inner perimeter
; feature outer perimeter
; layer 31, Z = 6.400
; feature inner perimeter
; feature outer perimeter
; layer 32, Z = 6.600
; feature inner perimeter
; feature outer perimeter
; layer 33, Z = 6.800
; feature inner perimeter
; feature outer perimeter
; layer 34, Z = 7.000
; feature inner perimeter
; feature outer perimeter
; layer 35, Z = 7.200
; feature inner perimeter
; feature outer perimeter
; layer 36, Z = 7.400
; feature inner perimeter
; feature outer perimeter
; layer 37, Z = 7.600
; feature inner perimeter
; feature outer perimeter
; layer 38, Z = 7.800
; feature inner perimeter
; feature outer perimeter
; layer 39, Z = 8.000
; feature inner perimeter
; feature outer perimeter
; layer 40, Z = 8.200
; feature inner perimeter
; feature outer perimeter
; layer 41, Z = 8.400
; feature inner perimeter
; feature outer perimeter
; layer 42, Z = 8.600
; feature inner perimeter
; feature outer perimeter
; layer 43, Z = 8.800
; feature inner perimeter
; feature outer perimeter
; layer 44, Z = 9.000
; feature inner perimeter
; feature outer perimeter
; layer 45, Z = 9.200
; feature inner perimeter
; feature outer perimeter
; layer 46, Z = 9.400
; feature inner perimeter
; feature outer perimeter
; layer 47, Z = 9.600
; feature inner perimeter
; feature outer perimeter
; layer 48, Z = 9.800
; feature inner perimeter
; feature outer perimeter
; layer 49, Z = 10.000
; feature inner perimeter
; feature outer perimeter
; layer 50, Z = 10.200
; feature inner perimeter
; feature outer perimeter
; layer 51, Z = 10.400
; feature inner perimeter
; feature outer perimeter
; layer 52, Z = 10.600
; feature inner perimeter
; feature outer perimeter
; layer 53, Z = 10.800
; feature inner perimeter
; feature outer perimeter
; layer 54, Z = 11.000
; feature inner perimeter
; feature outer perimeter
; layer 55, Z = 11.200
; feature inner perimeter
; feature outer perimeter
; layer 56, Z = 11.400
; feature inner perimeter
; feature outer perimeter
; layer 57, Z = 11.600
; feature inner perimeter
; feature outer perimeter
; layer 58, Z = 11.800
; feature inner perimeter
; feature outer perimeter
; layer 59, Z = 12.000
; feature inner perimeter
; feature outer perimeter
; layer 60, Z = 12.200
; feature inner perimeter
; feature outer perimeter
; layer 61, Z = 12.400
; feature inner perimeter
; feature outer perimeter
; layer 62, Z = 12.600
; feature inner perimeter
; feature outer perimeter
; layer 63, Z = 12.800
; feature inner perimeter
; feature outer perimeter
; layer 64, Z = 13.000
; feature inner perimeter
; feature outer perimeter
; layer 65, Z = 13.200
; feature inner perimeter
; feature outer perimeter
; layer 66, Z = 13.400
; feature inner perimeter
; feature outer perimeter
; layer 67, Z = 13.600
; feature inner perimeter
; feature outer perimeter
; layer 68, Z = 13.800
; feature inner perimeter
; feature outer perimeter
; layer 69, Z = 14.000
; feature inner perimeter
; feature outer perimeter
; layer 70, Z = 14.200
; feature inner perimeter
; feature outer perimeter
; layer 71, Z = 14.400
; feature inner perimeter
; feature outer perimeter
; layer 72, Z = 14.600
; feature inner perimeter
; feature outer perimeter
; layer 73, Z = 14.800
; feature inner perimeter
; feature outer perimeter
; layer 74, Z = 15.000
; feature inner perimeter
; feature outer perimeter
; layer 75, Z = 15.200
; feature inner perimeter
; feature outer perimeter
; layer 76, Z = 15.400
; feature inner perimeter
; feature outer perimeter
; layer 77, Z = 15.600
; feature inner perimeter
; feature outer perimeter
; layer 78, Z = 15.800
; feature inner perimeter
; feature outer perimeter
; layer 79, Z = 16.000
; feature inner perimeter
; feature outer perimeter
; layer 80, Z = 16.200
; feature inner perimeter
; feature outer perimeter
; layer 81, Z = 16.400
; feature inner perimeter
; feature outer perimeter
; layer 82, Z = 16.600
; feature inner perimeter
; feature outer perimeter
; layer 83, Z = 16.800
; feature inner perimeter
; feature outer perimeter
; layer 84, Z = 17.000
; feature inner perimeter
; feature outer perimeter
; layer 85, Z = 17.200
; feature inner perimeter
; feature outer perimeter
; layer 86, Z = 17.400
; feature inner perimeter
; feature outer perimeter
; layer 87, Z = 17.600
; feature inner perimeter
; feature outer perimeter
; layer 88, Z = 17.800
; feature inner perimeter
; feature outer perimeter
; layer 89, Z = 18.000
; feature inner perimeter
; feature outer perimeter
; layer 90, Z = 18.200
; feature inner perimeter
; feature outer perimeter
; layer 91, Z = 18.400
; feature inner perimeter
; feature outer perimeter
; layer 92, Z = 18.600
; feature inner perimeter
; feature outer perimeter
; layer 93, Z = 18.800
; feature inner perimeter
; feature outer perimeter
; layer 94, Z = 19.000
; feature inner perimeter
; feature outer perimeter
; layer 95, Z = 19.200
; feature inner perimeter
; feature outer perimeter
; layer 96, Z = 19.400
; feature inner perimeter
; feature outer perimeter
; layer 97, Z = 19.600
; feature inner perimeter
; feature outer perimeter
; layer 98, Z = 19.800
; feature inner perimeter
; feature outer perimeter
; layer 99, Z = 20.000
; feature inner perimeter
; feature outer perimeter
; layer 100, Z = 20.200
; feature inner perimeter
; feature outer perimeter
; layer 101, Z = 20.400
; feature inner perimeter
; feature outer perimeter
; layer 102, Z = 20.600
; feature inner perimeter
; feature outer perimeter
; layer 103, Z = 20.800
; feature inner perimeter
; feature outer perimeter
; layer 104, Z = 21.000
; feature inner perimeter
; feature outer perimeter
; layer 105, Z = 21.200
; feature inner perimeter
; feature outer perimeter
; layer 106, Z = 21.400
; feature inner perimeter
; feature outer perimeter
; layer 107, Z = 21.600
; feature inner perimeter
; feature outer perimeter
; layer 108, Z = 21.800
; feature inner perimeter
; feature outer perimeter
; layer 109, Z = 22.000
; feature inner perimeter
; feature outer perimeter
; layer 110, Z = 22.200
; feature inner perimeter
; feature outer perimeter
; layer 111, Z = 22.400
; feature inner perimeter
; feature outer perimeter
; layer 112, Z = 22.600
; feature inner perimeter
; feature outer perimeter
; layer 113, Z = 22.800
; feature inner perimeter
; feature outer perimeter
; layer 114, Z = 23.000
; feature inner perimeter
; feature outer perimeter
; layer 115, Z = 23.200
; feature inner perimeter
; feature outer perimeter
; layer 116, Z = 23.400
; feature inner perimeter
; feature outer perimeter
; layer 117, Z = 23.600
; feature inner perimeter
; feature outer perimeter
; layer 118, Z = 23.800
; feature inner perimeter
; feature outer perimeter
; layer 119, Z = 24.000
; feature inner perimeter
; feature outer perimeter
; layer 120, Z = 24.200
; feature inner perimeter
; feature outer perimeter
; layer 121, Z = 24.400
; feature inner perimeter
; feature outer perimeter
; layer 122, Z = 24.600
; feature inner perimeter
; feature outer perimeter
; layer 123, Z = 24.800
; feature inner perimeter
; feature outer perimeter
; layer 124, Z = 25.000
; feature inner perimeter
; feature outer perimeter
; layer 125, Z = 25.200
; feature inner perimeter
; feature outer perimeter
; layer 126, Z = 25.400
; feature inner perimeter
; feature outer perimeter
; layer 127, Z = 25.600
; feature inner perimeter
; feature outer perimeter
; layer 128, Z = 25.800
; feature inner perimeter
; feature outer perimeter
; layer 129, Z = 26.000
; feature inner perimeter
; feature outer perimeter
; layer 130, Z = 26.200
; feature inner perimeter
; feature outer perimeter
; layer 131, Z = 26.400
; feature inner perimeter
; feature outer perimeter
; layer 132, Z = 26.600
; feature inner perimeter
; feature outer perimeter
; layer 133, Z = 26.800
; feature inner perimeter
; feature outer perimeter
; layer 134, Z = 27.000
; feature inner perimeter
; feature outer perimeter
; layer 135, Z = 27.200
; feature inner perimeter
; feature outer perimeter
; layer 136, Z = 27.400
; feature inner perimeter
; feature outer perimeter
; layer 137, Z = 27.600
; feature inner perimeter
; feature outer perimeter
; layer 138, Z = 27.800
; feature inner perimeter
; feature outer perimeter
; layer 139, Z = 28.000
; feature inner perimeter
; feature outer perimeter
; layer 140, Z = 28.200
; feature inner perimeter
; feature outer perimeter
; layer 141, Z = 28.400
; feature inner perimeter
; feature outer perimeter
; layer 142, Z = 28.600
; feature inner perimeter
; feature outer perimeter
; layer 143, Z = 28.800
; feature inner perimeter
; feature outer perimeter
; layer 144, Z = 29.000
; feature inner perimeter
; feature outer perimeter
; layer 145, Z = 29.200
; feature inner perimeter
; feature outer perimeter
; layer 146, Z = 29.400
; feature inner perimeter
; feature outer perimeter
; layer 147, Z = 29.600
; feature inner perimeter
; feature outer perimeter
; layer 148, Z = 29.800
; feature inner perimeter
; feature outer perimeter
; layer 149, Z = 30.000
; feature inner perimeter
; feature outer perimeter
; layer 150, Z = 30.200
; feature inner perimeter
; feature outer perimeter
; layer 151, Z = 30.400
; feature inner perimeter
; feature outer perimeter
; layer 152, Z = 30.600
; feature inner perimeter
; feature outer perimeter
; layer 153, Z = 30.800
; feature inner perimeter
; feature outer perimeter
; layer 154, Z = 31.000
; feature inner perimeter
; feature outer perimeter
; layer 155, Z = 31.200
; feature inner perimeter
; feature outer perimeter
; layer 156, Z = 31.400
; feature inner perimeter
; feature outer perimeter
; layer 157, Z = 31.600
; feature inner perimeter
; feature outer perimeter
; layer 158, Z = 31.800
; feature inner perimeter
; feature outer perimeter
; layer 159, Z = 32.000
; feature inner perimeter
; feature outer perimeter
; layer 160, Z = 32.200
; feature inner perimeter
; feature outer perimeter
; layer 161, Z = 32.400
; feature inner perimeter
; feature outer perimeter
; layer 162, Z = 32.600
; feature inner perimeter
; feature outer perimeter
; layer 163, Z = 32.800
; feature inner perimeter
; feature outer perimeter
; layer 164, Z = 33.000
; feature inner perimeter
; feature outer perimeter
; layer 165, Z = 33.200
; feature inner perimeter
; feature outer perimeter
; layer 166, Z = 33.400
; feature inner perimeter
; feature outer perimeter
; layer 167, Z = 33.600
; feature inner perimeter
; feature outer perimeter
; layer 168, Z = 33.800
; feature inner perimeter
; feature outer perimeter
; layer 169, Z = 34.000
; feature inner perimeter
; feature outer perimeter
; layer 170, Z = 34.200
; feature inner perimeter
; feature outer perimeter
; layer 171, Z = 34.400
; feature inner perimeter
; feature outer perimeter
; layer 172, Z = 34.600
; feature inner perimeter
; feature outer perimeter
; layer 173, Z = 34.800
; feature inner perimeter
; feature outer perimeter
; layer 174, Z = 35.000
; feature inner perimeter
; feature outer perimeter
; layer 175, Z = 35.200
; feature inner perimeter
; feature outer perimeter
; layer 176, Z = 35.400
; feature inner perimeter
; feature outer perimeter
; layer 177, Z = 35.600
; feature inner perimeter
; feature outer perimeter
; layer 178, Z = 35.800
; feature inner perimeter
; feature outer perimeter
; layer 179, Z = 36.000
; feature inner perimeter
; feature outer perimeter
; layer end
; Build Summary
;   Build time: 2 hours 40 minutes
;   Filament length: 5609.6 mm (5.61 m)
;   Plastic volume: 13492.73 mm^3 (13.49 cc)
;   Plastic weight: 16.87 g (0.04 lb)
;   Material cost: 0.40
