import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, test } from "vitest";
import { parseSlicerFile } from "./index";
import { flushMatrix, purgeWaste, sequenceFromLayers, toolSequence } from "./waste";

const fixture = (f: string) => new Uint8Array(readFileSync(resolve(__dirname, "../../../tests/fixtures/slicer", f)));
const enc = (s: string) => new TextEncoder().encode(s);

describe("desperdício multicor (#147)", () => {
  test("3MF real da A1 (2 cores): 1 troca azul → branco purga 616 mm³ ≈ 0,78 g, fora do used_g", () => {
    const r = parseSlicerFile("bambu-a1-2cores-fatiado.3mf", fixture("bambu-a1-2cores-fatiado.3mf"));
    expect(r.filaments.map((f) => f.grams)).toEqual([3.79, 0.55]); // o consumo do fatiador fica como está
    expect(r.waste).toEqual({ byFilament: [{ index: 2, grams: 0.78 }], grams: 0.78, swaps: 1, included: false, from: "camadas" });
  });

  test("matriz n×n: linha = de, coluna = para; lista que não é quadrada é ignorada", () => {
    expect(flushMatrix([0, 616, 229, 0])).toEqual([
      [0, 616],
      [229, 0],
    ]);
    expect(flushMatrix([1, 2, 3])).toBeNull();
    expect(flushMatrix([])).toBeNull();
  });

  test("sequência pelo G-code: M620 S<n>A e T<n>, sem repetir e sem o descarregar (255)", () => {
    const g = ["M620 S0A", "T0", "G1 X1", "M620 S1A ; troca", "T1", "M620 S2A", "M620 S0A", "M620 S255", "T255"].join("\n");
    expect(toolSequence(g)).toEqual([0, 1, 2, 0]);
  });

  test("sequência pelas camadas (4 cores): cada camada começa na cor em que a anterior terminou", () => {
    const seq = sequenceFromLayers([
      { filaments: [0], from: 0, to: 4 },
      { filaments: [0, 1], from: 5, to: 6 },
      { filaments: [2, 3], from: 7, to: 7 },
    ]);
    // camada 5: 0 → 1; camada 6 começa no 1 e troca para o 0; camada 7 (sem o 0): 2 → 3
    expect(seq).toEqual([0, 1, 0, 2, 3]);
  });

  test("purga cobrada do filamento que entra, com a densidade dele e o multiplicador", () => {
    const m = flushMatrix([0, 500, 300, 200, 0, 400, 100, 250, 0])!;
    const w = purgeWaste([0, 1, 2, 0], m, 1.5, (i) => [1.24, 1.27, 1.04][i], "gcode")!;
    // 0→1: 500 mm³ × 1,5 × 1,27; 1→2: 400 × 1,5 × 1,04; 2→0: 100 × 1,5 × 1,24
    expect(w.byFilament).toEqual([
      { index: 1, grams: 0.19 },
      { index: 2, grams: 0.95 },
      { index: 3, grams: 0.62 },
    ]);
    expect(w.swaps).toBe(3);
    expect(purgeWaste([0], m, 1, () => 1.24, "gcode")).toBeNull(); // uma cor só: sem purga
  });

  test("G-code do Bambu com trocas: purga calculada pela matriz do próprio arquivo", () => {
    const g = [
      "; HEADER_BLOCK_START",
      "; BambuStudio 02.08.02.61",
      "; total estimated time: 30m 0s",
      "; total filament weight [g] : 10.00,2.00",
      "; HEADER_BLOCK_END",
      "; flush_volumes_matrix = 0,616,229,0",
      "; flush_multiplier = 1",
      "; filament_density: 1.26,1.26",
      "M620 S0A",
      "M620 S1A",
      "M620 S0A",
      "M620 S1A",
    ].join("\n");
    const r = parseSlicerFile("x.gcode", enc(g));
    // 0→1 (616) + 1→0 (229) + 0→1 (616) = 1461 mm³
    expect(r.waste).toMatchObject({ swaps: 3, included: false, from: "gcode", grams: 1.84 });
    expect(r.waste!.byFilament).toEqual([
      { index: 1, grams: 0.29 },
      { index: 2, grams: 1.55 },
    ]);
  });

  test("PrusaSlicer/Orca: a torre já está no consumo; só informa", () => {
    const g = ["; generated by PrusaSlicer 2.8.1", "; filament used [g] = 12.5, 4.0", "; total filament used for wipe tower [g] = 3.20", "; estimated printing time (normal mode) = 1h 2m 3s"].join("\n");
    expect(parseSlicerFile("x.gcode", enc(g)).waste).toEqual({ byFilament: [], grams: 3.2, swaps: 0, included: true, from: "torre" });
  });

  test("uma cor só (G-code real do Cura): sem desperdício", () => {
    expect(parseSlicerFile("cura-1cor.gcode", fixture("cura-1cor.gcode")).waste).toBeUndefined();
  });
});
